import { API_PATHS } from '../../scripts/lib/doc-api-contract.mjs';

export const PAGE_BASE = new URL('./', location.href);
export const DATA_INDEX_URL = new URL('data/index.json', PAGE_BASE).href;
export const ASSET_BASE_URL = new URL('../', PAGE_BASE).href;
export const DOC_CAPABILITIES_URL = new URL(API_PATHS.CAPABILITIES, PAGE_BASE).href;
export const DOC_HEALTH_URL = new URL(API_PATHS.HEALTH, PAGE_BASE).href;
export const DOC_API_URL = new URL(API_PATHS.DOC, PAGE_BASE).href;
export const DOC_REBUILD_URL = new URL(API_PATHS.REBUILD, PAGE_BASE).href;

export const appState = {
  docs: [],
  activePath: '',
  activeTab: 'all',
  generatedStatus: '',
  editInputMode: 'source',
  editBlockDrafts: [],
  editHasUnsavedChanges: false,
  mode: 'browse',
  editBackendAvailable: false,
  isEditing: false,
  isRebuilding: false,
  isCreating: false,
  isCreatePathValid: true,
  activeCreateType: 'hero',
  activeEditPath: '',
  activeEditSource: '',
  activeCreatePath: '',
  activeEditSourceVersion: '',
};

export const domElements = {
  statusEl: document.getElementById('status'),
  listEl: document.getElementById('docList'),
  loadRetryBtnEl: document.getElementById('docLoadRetryBtn'),
  searchInput: document.getElementById('searchInput'),
  searchClearEl: document.getElementById('searchClear'),
  categoryTabsEl: document.getElementById('categoryTabs'),
  titleEl: document.getElementById('docTitle'),
  subtitleEl: document.getElementById('docSubtitle'),
  typeChipEl: document.getElementById('docTypeChip'),
  groupChipEl: document.getElementById('docGroupChip'),
  pathChipEl: document.getElementById('docPathChip'),
  bannerEl: document.getElementById('heroBanner'),
  metaEl: document.getElementById('metaCards'),
  sectionEl: document.getElementById('sectionCards'),
  contentEl: document.getElementById('docContent'),
  galleryEl: document.getElementById('heroGallery'),
  editActionsEl: document.getElementById('docEditActions'),
  editCreateBtnEl: document.getElementById('docCreateBtn'),
  editBtnEl: document.getElementById('docEditBtn'),
  editSaveBtnEl: document.getElementById('docSaveBtn'),
  editCancelBtnEl: document.getElementById('docCancelBtn'),
  editRebuildBtnEl: document.getElementById('docRebuildBtn'),
  editPathEl: document.getElementById('docEditPath'),
  editDirtyIndicatorEl: document.getElementById('docEditDirtyIndicator'),
  saveConflictDialogEl: document.getElementById('docSaveConflictDialog'),
  saveConflictDialogTitleEl: document.getElementById('docSaveConflictDialogTitle'),
  saveConflictDialogMessageEl: document.getElementById('docSaveConflictDialogMessage'),
  saveConflictDialogWarningEl: document.getElementById('docSaveConflictDialogWarning'),
  saveConflictReloadBtnEl: document.getElementById('docSaveConflictReloadBtn'),
  saveConflictKeepBtnEl: document.getElementById('docSaveConflictKeepBtn'),
  saveConflictForceBtnEl: document.getElementById('docSaveConflictForceBtn'),
  saveConflictCancelBtnEl: document.getElementById('docSaveConflictCancelBtn'),
  editModeBarEl: document.getElementById('docEditModeBar'),
  editSourceModeBtnEl: document.getElementById('docEditSourceModeBtn'),
  editBlockModeBtnEl: document.getElementById('docEditBlockModeBtn'),
  editBlockEditorEl: document.getElementById('docBlockEditor'),
  createTypeWrapEl: document.getElementById('docCreateTypeWrap'),
  createTypeSelectEl: document.getElementById('docCreateTypeSelect'),
  createPathWrapEl: document.getElementById('docCreatePathWrap'),
  createPathInputEl: document.getElementById('docCreatePathInput'),
  editStatusEl: document.getElementById('docEditStatus'),
  editEditorEl: document.getElementById('docSourceEditor'),
  modeSwitchEl: document.getElementById('modeSwitch'),
  modeBrowseBtnEl: document.getElementById('modeBrowseBtn'),
  modeEditBtnEl: document.getElementById('modeEditBtn'),
  modeStateEl: document.getElementById('modeStateChip'),
  editPanelEl: document.getElementById('docEditPanel'),
  docEditorWrapEl: document.getElementById('docEditorWrap'),
  leftTotalStatEl: document.getElementById('leftTotalStat'),
  leftVisibleStatEl: document.getElementById('leftVisibleStat'),
  leftLegendBodyEl: document.getElementById('leftLegendBody'),
  runtimeErrorPanelEl: document.getElementById('runtimeErrorPanel'),
  runtimeErrorListEl: document.getElementById('runtimeErrorList'),
  runtimeErrorClearBtnEl: document.getElementById('runtimeErrorClearBtn'),
};

export const EDITABLE_SOURCE_PREFIXES = ['design-data/', 'docs-standard/design-data/'];

export const APP_ERROR_MESSAGES = {
  unsavedConfirmDefault: '放弃后，当前编辑未保存内容将丢失，是否继续？',
  runtimeContextDefault: '运行时',
  readLatestSourceFailure: '读取最新内容失败',
  saveConflictCancelled: '已取消保存：版本冲突处理已中止。',
  templateLoadFallback: '模板加载失败，已使用空模板',
  saveConflictTitle: '保存冲突',
  forceSaveConfirmTitle: '强制覆盖确认',
  saveConflictHeader: (latestLabel) => `保存冲突：文档已被其他会话更新（最新版本：${latestLabel}）。`,
  saveConflictOptions: {
    loadLatest: '1) 载入服务器最新内容并放弃当前草稿',
    keepDraft: '2) 保留当前草稿，放弃这次保存',
    forceSave: '3) 强制覆盖（会覆盖他人最新修改，存在风险）',
  },
  forceSaveConfirmMessages: {
    confirmTitle: '确定要执行“强制覆盖”吗？',
    versionLabelPrefix: '目标版本：',
    overwriteWarn: '强制覆盖将覆盖该版本内容，可能覆盖其他编辑者的最新修改。',
    finalConfirm: '请再次确认，是否继续？',
    forceButton: '确认覆盖',
    forceWarning: '⚠️ 危险操作：此操作会覆盖当前已存在的版本。请确认无误后再继续。',
  },
  forceSaveActionButton: '强制覆盖',
  conflictReloadMessage: '已加载服务器最新内容，你可以基于该内容继续编辑并保存。',
  conflictKeepDraftMessage: '已保留当前草稿，请在确认内容后重试保存。',
  discardUnsavedModeExit: '当前有未保存内容，切换到浏览模式将丢失这些修改，是否继续？',
  discardUnsavedCreate: '当前有未保存内容，进入新建将丢失这些修改，是否继续？',
  discardUnsavedEditExit: '当前有未保存内容，放弃编辑并返回浏览？',
  discardUnsavedSwitchDoc: '当前有未保存内容，切换文档将丢失这些修改，是否继续？',
  noEditablePath: '该文档当前未绑定到可编辑源文件',
  loadingSource: '正在读取源文档...',
  savingSource: '正在保存源码...',
  requestTimeout: '请求超时，请稍后重试',
  requestUnauthorized: '未登录或授权已失效，请重新登录后重试',
  requestMissingToken: '未检测到编辑令牌，保存编辑前请先配置令牌',
  requestInvalidToken: '编辑令牌无效或已失效，请检查并更新令牌',
  requestUnauthorizedHint: '请确认当前页面登录状态已刷新，或重新打开编辑页面后再试',
  requestForbidden: '当前账号没有写入文档的权限',
  requestForbiddenHint: '请使用具备文档写权限的账号后重试，或联系管理员授予权限',
  requestRateLimited: '请求过于频繁，请稍后再试',
  requestRateLimitedHint: (retryAfterText) => retryAfterText
    ? `服务限制中，建议 ${retryAfterText} 秒后重试`
    : '服务限制中，请稍后再试',
  requestUnsupportedMediaType: '请求体类型不支持，请使用 application/json',
  requestUnsupportedMediaTypeHint: (pathHint = '') => pathHint
    ? `请检查 ${pathHint} 接口请求头是否包含正确的 Content-Type`
    : '请检查请求头是否包含正确的 Content-Type',
  requestPayloadTooLarge: '提交内容过大，请减少内容后重试',
  requestServerError: '服务端异常，请稍后再试',
  requestServerErrorHint: '服务端可能在重启或部署窗口，稍后请再尝试',
  requestInvalidResponse: '后端返回了非预期响应格式',
  serviceUnavailable: '服务当前不可用，请稍后重试',
  saveConflict: '保存失败：该文档已被其他会话更新，已触发编辑锁冲突，请先刷新文档后重试',
  saveMissingContent: '保存失败：保存内容为空',
  saveDocMissing: '保存失败：文档不存在，可能已被删除',
  saveSuccess: '保存成功，正在重建索引...',
  createSuccess: '新建成功，正在重建索引...',
  createPathRequired: '请先填写新建路径',
  createPathInvalid: '新建路径无效',
  createPathExists: '路径已存在，请更换新建路径',
  createPathPlaceholder: '请输入可编辑路径（如 design-data/xxx.txt）',
  createDocHintTemplate: (createActionLabel) => `输入新建路径与内容后，点击“${createActionLabel}”`,
  generatedStatusTemplate: (generatedAtText) => `（静态生成 ${generatedAtText}）`,
  rebuildStarting: '重建索引中...',
  rebuildSuccess: '重建完成，文档已刷新',
  rebuildElapsedTemplate: (elapsedText) => `（耗时 ${elapsedText}）`,
  rebuildInProgress: '重建中',
  rebuildFailed: '重建失败，请稍后重试',
  editModeUnavailable: '当前后端未开启编辑接口，已切到浏览模式。',
  editBackendUnavailableReasons: {
    available: '',
    capabilities_disabled: '服务返回编辑能力为关闭状态',
    capabilities_http_404: '未检测到编辑能力接口',
    capabilities_invalid: '编辑能力返回结构异常',
    capabilities_missing_edit_flag: '编辑能力数据缺少编辑能力字段',
    health_no_edit_info: '检测到健康服务，但未检测到可写能力',
    health_invalid: '健康检查返回异常',
    health_unavailable: '后端健康检查不可用',
    service_unreachable: '文档服务不可达',
  },
  granularEditUnavailable: '当前文档不支持区块编辑，已切到源码模式。',
  createPathValidation: {
    absolutePath: '路径不能是绝对路径',
    dotSegment: '路径不能包含 . 或 .. 路径段',
    basePrefix: '路径必须以 design-data/ 或 docs-standard/design-data/ 开头',
    trailingSlash: '路径不能以 / 结尾',
    invalidChars: '路径包含非法字符',
  },
  readDocSourceParamsInvalid: '读取源码请求参数不完整',
  templatePathRequired: '模板路径不能为空',
  templateInvalidContentType: '模板内容不合法（返回了 HTML）',
  saveDocParamsInvalid: '保存请求参数不完整',
  rebuildIndexParamsInvalid: '重建请求参数不完整',
  lockVersionMissing: '未获取到当前文件的编辑锁版本，请刷新后重试',
};

export const APP_REQUEST_LABELS = {
  detectEditCapability: '检测编辑能力',
  loadDocIndex: '加载文档索引',
  loadTemplate: '加载模板',
  readSource: '读取源码',
  createDoc: '创建',
  saveDoc: '保存',
  rebuildIndex: '重建索引',
  templateLoad: '模板加载',
};

export const APP_RUNTIME_TEXTS = {
  modeState: {
    editBackendUnavailable: '编辑模式（后端未接入）',
    editNoDoc: '编辑模式（请选择文档）',
    editActive: '编辑模式',
    editDocReadonly: '编辑模式（当前文档不可编辑）',
    browse: '浏览模式',
    browseNoEditApi: '浏览模式（编辑接口不可用）',
    editModeNeedBackendTitle: '编辑模式需要启动 /api 服务',
  },
  editPath: {
    sourcePrefix: '可编辑源：',
    sourceMissing: '—',
    noBackend: '可编辑源：编辑模式未开启',
    browseMode: '可编辑源：当前为浏览模式',
    nonEditableDoc: '可编辑源：当前文档不可直接编辑',
  },
  editButtons: {
    editText: '编辑',
    returnText: '返回',
  },
  editBlock: {
    noBlockHint: '该文档暂无可编辑结构区块，可直接切到源码模式修改。',
    blockTypePrefix: '区块',
    blockTypeSeparator: '·',
    defaultBlockType: 'text',
  },
  runtimeContext: {
    contentRender: '内容渲染',
    listRender: '文档列表渲染',
    docSwitchRender: '文档切换渲染',
    listNode: '列表项',
    category: '分类',
    group: '分组',
    indexLoadFailed: '未成功获取文档索引',
    indexFormatInvalid: '文档索引格式异常',
    dataCategoryInvalid: '分类数据异常',
    dataGroupInvalid: '分组数据异常',
    globalError: '前端全局错误',
    unhandledPromise: '未处理的Promise错误',
    init: '初始化',
  },
  heroSkill: {
    heading: '技能图标与说明',
    duplicateSectionTitles: ['技能树', '技能说明'],
    fallbackName: '技能',
    mediaFallbackLabel: '媒体',
    mediaImageAltSuffix: '图标',
    mediaPlaceholderSuffix: '占位图',
    sectionKeyDefault: '技能',
  },
  listMeta: {
    typeLabelPrefix: '类型：',
    noMatchStatus: '暂无命中文档',
    permissionEditable: '可编辑',
    permissionReadonly: '不可编辑',
  },
  list: {
    status: {
      loadingIndex: '正在加载文档索引…',
      loadingList: '加载文档列表…',
      renderingList: '正在渲染文档列表…',
      retryIndex: '正在重试加载文档索引…',
      retryLoading: '重试加载中…',
      initializing: '正在初始化文档站…',
      initializingList: '初始化中…',
      initFailed: '初始化失败',
      initListFailure: '初始化失败，请刷新页面后重试。',
      skeleton: '正在加载文档列表…',
      visibleCountTemplate: (visibleCount, totalCount) => `当前显示 ${visibleCount} 个文档（共 ${totalCount} 个）`,
      noDataByKeyword: '未匹配到文档',
      noDataByTab: '当前标签暂无文档',
      filteredTagText: '（已按关键词筛选）',
      categoryPrefix: '分类',
      groupPrefix: '分组',
      groupChipPrefix: '分组',
      pathChipPrefix: '路径',
    },
    labels: {
      pathSuffixError: '文档内容渲染失败',
      renderFailedStatus: '渲染失败',
      genericRenderFailed: '文档渲染失败',
    },
    actions: {
      retryText: '重试加载',
      retryForceText: '清缓存重试',
      retryListTitle: '重新加载文档索引并刷新列表',
    },
    errors: {
      nodeDefaultContext: '列表项',
      loadFailureText: '文档列表加载失败',
      loadFailureSuffix: '。请确认服务运行正常并重试。',
      renderFailureText: '文档列表渲染失败',
      genericLoadFailureText: '加载失败',
      unknownEntry: '未知条目',
      contextLoadFailureTemplate: (context, message) => `${context}加载失败：${message}`,
      duplicatePrefix: '重复错误省略（已出现',
      duplicateSuffix: '次）',
      latestErrorLabel: '最近一次错误码/状态（展开）',
      statusLabel: '状态：',
      requestCodeLabel: '错误码：',
      rawMessageLabel: '原始信息：',
      detailLabel: '错误详情：',
      descriptionLabel: '错误描述：',
    },
  summary: {
      label: '列表渲染异常',
      topLabel: '，集中在：',
      unitLabel: '处问题',
      moreLabel: '更多',
      moreSuffix: '项（展开）',
      countTemplate: (context, count) => `${context}：${count}次`,
    },
    otherFallback: '其他',
  },
  create: {
    prefix: '新建',
    sourcePrefix: '新建源（',
    sourceTypeSuffix: '）：',
    defaultName: '新建文档',
    hero: '新建英雄',
    item: '新建物品',
    unit: '新建单位',
    skill: '新建技能',
    building: '新建建筑',
    backstory: '新建背景故事',
    scene: '新建场景',
    rule: '新建规则',
    template: '新建模板',
    fallbackSceneByTemplateSource: '新建场景',
  },
  createTypeSwitchConfirm: '切换新建类型将重置当前内容，是否继续？',
  pageShell: {
    documentTitle: 'Epic of Viento Line 文档站',
    siteTitle: 'Epic of Viento Line 文档站',
    siteSubtitle: 'Dota2 风格档案浏览 · 统一由 docs-standard 渲染',
    topbarNavAriaLabel: '主导航',
    navCatalog: '文档库',
    navHero: '英雄',
    navItem: '物品',
    navUnit: '单位',
    modeSwitchAriaLabel: '模式切换',
    modeBrowseBtn: '浏览',
    modeEditBtn: '编辑',
    searchPlaceholder: '搜索文档名 / 标签',
    searchClearText: '清空搜索',
    searchClearAria: '清空搜索',
    categoryTabsAriaLabel: '文档分类选项卡',
    runtimeErrorTitle: '最近错误',
    runtimeErrorClearText: '清空',
    runtimeErrorClearAria: '清空错误记录',
    leftPanelAriaLabel: '列表统计',
    totalDocsLabel: '库内文档',
    visibleDocsLabel: '当前展示',
    legendAriaLabel: '分类分布',
    legendTitle: '分类分布',
    docListLoadingPlaceholder: '正在加载文档列表…',
    docTypeChipPlaceholder: '未选择类型',
    docGroupChipPlaceholder: '未选择分组',
    docPathChipPrefix: '路径',
    docPathChipSuffix: '—',
    docTitlePlaceholder: '未选择文档',
    docSubtitlePlaceholder: '请选择左侧文档后查看细节',
    editableSourcePrefixPlaceholder: '可编辑源：—',
    unsavedIndicatorText: '未保存',
    createButtonText: '新建文档',
    editButtonText: '编辑',
    saveButtonText: '保存',
    cancelButtonText: '取消',
    rebuildIndexButtonText: '重建索引',
    createTypeLabelText: '新建类型',
    createPathLabelText: '新建路径（例如: design-data/xxx.txt）',
    createPathPlaceholder: 'design-data/xxx.txt',
    sourceModeText: '源码',
    blockModeText: '区块',
    editorPlaceholderText: '编辑文档内容',
    contentPlaceholderText: '请先在左侧选择一份文档。',
    conflictDialogTitle: '保存冲突',
    conflictReloadActionText: '载入最新（放弃草稿）',
    conflictKeepActionText: '保留草稿',
    conflictForceActionText: '强制覆盖',
    conflictCancelActionText: '取消',
  },
};

export const TAB_DEFINITIONS = [
  { id: 'all', label: '全部' },
  { id: 'hero', label: '英雄' },
  { id: 'item', label: '物品' },
  { id: 'other', label: '其他' },
];

export const CATEGORY_LABELS = {
  hero: '英雄',
  item: '物品',
  unit: '单位',
  skill: '技能',
  building: '建筑',
  backstory: '背景故事',
  scene: '场景',
  rule: '规则',
  template: '模板',
  root: '项目文档',
  other: '其他',
};

export const CATEGORY_TAG = {
  hero: 'hero',
  item: 'item',
  unit: 'unit',
  skill: 'skill',
  building: 'building',
  backstory: 'story',
  scene: 'scene',
  rule: 'rule',
  template: 'template',
  root: 'root',
  other: 'other',
};

export const CATEGORY_ORDER = [
  'hero',
  'item',
  'unit',
  'skill',
  'backstory',
  'scene',
  'rule',
  'building',
  'template',
  'root',
  'other',
];

export const BACKSTORY_CHUNK_SIZE = 640;
